# Generated by Django 5.1.6 on 2025-03-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_forabout', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('work_experience', models.CharField(max_length=500)),
                ('work_experience_detail', models.CharField(max_length=1000)),
                ('main_skills', models.CharField(max_length=100)),
                ('skill_01', models.CharField(max_length=100)),
                ('skill_01_detail', models.CharField(max_length=100)),
                ('skill_02', models.CharField(max_length=100)),
                ('skill_02_detail', models.CharField(max_length=100)),
                ('skill_03', models.CharField(max_length=100)),
                ('skill_03_detail', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('education_01', models.CharField(max_length=100)),
                ('education_01_detail', models.CharField(max_length=100)),
                ('education_02', models.CharField(max_length=100)),
                ('education_02_detail', models.CharField(max_length=100)),
                ('education_03', models.CharField(max_length=100)),
                ('education_03_detail', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=100)),
                ('other_01', models.CharField(max_length=100)),
                ('other_01_detail', models.CharField(max_length=100)),
                ('other_02', models.CharField(max_length=100)),
                ('other_02_detail', models.CharField(max_length=100)),
                ('other_03', models.CharField(max_length=100)),
                ('other_03_detail', models.CharField(max_length=100)),
            ],
        ),
    ]
