# Generated by Django 5.1.6 on 2025-03-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services01data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('head_about', models.CharField(max_length=100)),
                ('p_head', models.CharField(max_length=100)),
                ('p_about', models.CharField(max_length=100)),
                ('p_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='services02data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_head', models.CharField(max_length=100)),
                ('card_about', models.CharField(max_length=100)),
                ('card_link', models.URLField(max_length=500)),
            ],
        ),
    ]
