# Generated by Django 5.1.6 on 2025-03-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='part01data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('head_about', models.CharField(max_length=100)),
                ('btn01', models.CharField(max_length=100)),
                ('btn02', models.CharField(max_length=100)),
                ('btn03', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='part02data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn01_head', models.CharField(max_length=100)),
                ('btn01_about', models.CharField(max_length=100)),
                ('btn01_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='part03data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn03_head', models.CharField(max_length=100)),
                ('btn03_about', models.CharField(max_length=100)),
                ('btn03_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
