# Generated by Django 5.1.6 on 2025-03-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='part04data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn03_head', models.CharField(max_length=100)),
                ('btn03_about', models.CharField(max_length=100)),
                ('btn03_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='part03data',
            old_name='btn03_about',
            new_name='btn02_about',
        ),
        migrations.RenameField(
            model_name='part03data',
            old_name='btn03_head',
            new_name='btn02_head',
        ),
        migrations.RenameField(
            model_name='part03data',
            old_name='btn03_img',
            new_name='btn02_img',
        ),
    ]
