# Generated by Django 5.1.6 on 2025-03-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('positin', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='pdfs/')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
