# Generated by Django 5.1.6 on 2025-03-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skilldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_rate', models.IntegerField()),
                ('skill_name', models.CharField(max_length=100)),
            ],
        ),
    ]
