# Generated by Django 5.1.6 on 2025-03-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsapp', '0002_skilldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='footerdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_date', models.IntegerField()),
                ('copy_name', models.CharField(max_length=100)),
            ],
        ),
    ]
